Hufftree hufftreeCreateNode(Hufftree left, char chr, int frq, Hufftree right);
Hufftree hufftreeRemove(Hufftree *forest, int *qty);
Hufftree hufftreeCreate(char *string);
int *hufftreeFrequency(char *string);
void hufftreeInsert(Hufftree tree, Hufftree *forest, int *qty);
void hufftreeDisplay(Hufftree tree);
void hufftreeDisplayLeaves (Hufftree tree);
void hufftreeCreateTable(Hufftree tree, char *T[]);
void hufftreeCompressString(char *string, Hufftree tree);
void hufftreeDecompressString(char *string, Hufftree tree);
void hufftreeDestroy(Hufftree tree);